language: python

matrix:
  include:
    - python: "3.6"
    - python: "3.7"
      dist: xenial

# Need to install libgit2 manually to make sure we get a recent version
# of the development files – needed to build pygit2:
env: LIBGIT2=~/libgit2/_install/ LD_LIBRARY_PATH=~/libgit2/_install/lib

addons:
  apt:
    packages:
      - zsh
      - cmake

install:
  - "./.travis.sh"
  - pip install pygit2==0.26

script:
  - python tests.py
