language: python

python:
  - "3.3"

sudo: false


# Need to install libgit2 manually to make sure we get a recent version
# of the development files – needed to build pygit2:
env: LIBGIT2=~/libgit2/_install/ LD_LIBRARY_PATH=~/libgit2/_install/lib

# Dependencies can be installed as follows. This works only for packages
# whitelisted on https://github.com/travis-ci/apt-package-whitelist:
addons:
  apt:
    packages:
      - zsh
      - cmake

install:
  - "./.travis.sh"
  - pip install pygit2

script:
  - python tests.py
