#! /bin/zsh

set -e

local scripts=$(dirname $(readlink -f ${(%):-%x}))
local orig=$(readlink -f $1)
local dest=$(readlink -f $2)

git clone $orig $dest --mirror && cd $dest

python $scripts/git_filter_tree unpack -- --branches --tags

$scripts/git-compress
